version: '3'

services:
  homeassistant:
    container_name: mistborn_production_home_assistant 
    image: homeassistant/home-assistant:stable
    volumes:
      - ../../mistborn_volumes/extra/homeassistant/config:/config
    environment:
      - TZ=America/New_York
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant-http.rule=Host(`homeassistant.${MISTBORN_BASE_DOMAIN}`) && ${MISTBORN_ACCESS_RULE}"
      - "traefik.http.routers.homeassistant-http.entrypoints=web"
      - "traefik.http.routers.homeassistant-http.middlewares=mistborn_auth@docker"
      - "traefik.http.routers.homeassistant-https.rule=Host(`homeassistant.${MISTBORN_BASE_DOMAIN}`) && ${MISTBORN_ACCESS_RULE}"
      - "traefik.http.routers.homeassistant-https.entrypoints=websecure"
      - "traefik.http.routers.homeassistant-https.middlewares=mistborn_auth@docker"
      - "traefik.http.routers.homeassistant-https.tls.certresolver=mistbornresolver"
      - "traefik.http.services.homeassistant-service.loadbalancer.server.port=8123"
    restart: unless-stopped 

networks:
  default:
    external:
      name: mistborn_default
