version: '3'

services:  
  nextcloud:
    image: nextcloud
    container_name: mistborn_production_nextcloud
    env_file:
      - ../.envs/.production/.postgres
      - ../.envs/.production/.nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
    volumes:
      - ../../mistborn_volumes/extra/nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=nextcloud.mistborn
    restart: unless-stopped

networks:
  default:
    external:
      name: mistborn_default
