version: '3'

services:
  onlyoffice-document-server:
    container_name: mistborn_production_onlyoffice_documentserver
    image: onlyoffice/documentserver:latest
    volumes:
      - ../../mistborn_volumes/extra/onlyoffice/documentserver-data:/var/www/onlyoffice/Data
      - ../../mistborn_volumes/extra/onlyoffice/documentserver-logs:/var/log/onlyoffice
    env_file:
      - ../.envs/.production/.onlyoffice
    networks:
      onlyoffice_net:
    restart: unless-stopped 

  onlyoffice-mail-server:
    container_name: mistborn_production_onlyoffice_mailserver
    privileged: true
    image: onlyoffice/mailserver:latest
    volumes:
      - ../../mistborn_volumes/extra/onlyoffice/mailserver-data:/var/vmail
      - ../../mistborn_volumes/extra/onlyoffice/mailserver-certs:/etc/pki/tls/mailserver
      - ../../mistborn_volumes/extra/onlyoffice/mailserver-logs:/var/log
      - ../../mistborn_volumes/extra/onlyoffice/mailserver-mysql:/var/lib/mysql
    hostname: mistborn
    networks:
      onlyoffice_net:
    ports:
      - "25:25/tcp"
      - "143:143/tcp"
      - "587:587/tcp"
    restart: unless-stopped 

  onlyoffice-community-server:
    container_name: mistborn_production_onlyoffice_community_server
    image: onlyoffice/communityserver
    environment:
      - DOCUMENT_SERVER_PORT_80_TCP_ADDR=mistborn_production_onlyoffice_documentserver
      - MAIL_SERVER_DB_HOST=mistborn_production_onlyoffice_mailserver
    volumes:
      - ../../mistborn_volumes/extra/onlyoffice/communityserver-data:/var/www/onlyoffice/Data
      - ../../mistborn_volumes/extra/onlyoffice/communityserver-mysql:/var/lib/mysql
      - ../../mistborn_volumes/extra/onlyoffice/communityserver-logs:/var/log/onlyoffice
      - ../../mistborn_volumes/extra/onlyoffice/documentserver-data:/var/www/onlyoffice/DocumentServerData
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
    networks:
      onlyoffice_net:
    ports:
      - "5222:5222/tcp"
    restart: unless-stopped 


networks:
  default:
    external:
      name: mistborn_default

  onlyoffice_net:
    driver: bridge
