version: '3'

services:
  onlyoffice:
    container_name: mistborn_production_onlyoffice
    image: onlyoffice/documentserver:6.4.2.6
    volumes:
      - ../../mistborn_volumes/extra/onlyoffice/logs:/var/log/onlyoffice
      - ../../mistborn_volumes/extra/onlyoffice/cache:/var/lib/onlyoffice
    env_file:
      - ../.envs/.production/.onlyoffice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice-http.rule=Host(`onlyoffice.${MISTBORN_BASE_DOMAIN}`) && ${MISTBORN_ACCESS_RULE}"
      - "traefik.http.routers.onlyoffice-http.entrypoints=web"
      - "traefik.http.routers.onlyoffice-http.middlewares=mistborn_auth@file,onlyoffice-headers"
      - "traefik.http.routers.onlyoffice-https.rule=Host(`onlyoffice.${MISTBORN_BASE_DOMAIN}`) && ${MISTBORN_ACCESS_RULE}"
      - "traefik.http.routers.onlyoffice-https.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice-https.middlewares=mistborn_auth@file,onlyoffice-headers"
      - "traefik.http.routers.onlyoffice-https.tls.certresolver=mistbornresolver"
      - "traefik.http.services.onlyoffice-service.loadbalancer.server.port=80"
      # Headers for onlyoffice, https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/151
      - "traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.onlyoffice-headers.headers.accesscontrolalloworiginlist=*"
    restart: unless-stopped 

networks:
  default:
    external:
      name: mistborn_default
