version: '3'

services:
  raspap:
    build:
      context: ..
      dockerfile: ./compose/production/raspap/Dockerfile
    #user: root
    image: mistborn_production_raspap
    container_name: mistborn_production_raspap
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raspap-http.rule=Host(`raspap.mistborn`)"
      - "traefik.http.routers.raspap-http.entrypoints=web"
      - "traefik.http.routers.raspap-http.middlewares=mistborn_auth@file"
      - "traefik.http.routers.raspap-https.rule=Host(`raspap.mistborn`)"
      - "traefik.http.routers.raspap-https.entrypoints=websecure"
      - "traefik.http.routers.raspap-https.middlewares=mistborn_auth@file"
      - "traefik.http.routers.raspap-https.tls.certresolver=basic"
      - "traefik.http.services.raspap-service.loadbalancer.server.port=80"
    env_file:
      - ../.envs/.production/.pihole
    command: /start
    volumes:
      - ../../mistborn_volumes/extra/raspap/etc-raspap:/etc/raspap

networks:
  default:
    external:
      name: mistborn_default
