version: '3'

services:
  tor-client:
    build:
      context: ..
      dockerfile: ./compose/production/tor/Dockerfile
    image: mistborn_production_tor
    container_name: mistborn_production_tor
    ports:
      - 9150:9150/tcp

networks:
  default:
    external:
      name: mistborn_default
