version: '3'

services:
  wifi:
    #user: root
    image: "cyber5k/wifi:${MISTBORN_TAG}"
    container_name: mistborn_production_wifi
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.port=80"
    #env_file:
    #  - ../.envs/.production/.pihole
    #command: /start
    volumes:
      - ../../mistborn_volumes/extra/wifi/wificfg.json:/cfg/wificfg.json
    network_mode: host
    privileged: true

