[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/tls/cert.crt"
      keyFile = "/tls/cert.key"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"

[http.services]
  [http.services.cockpit.loadBalancer]
    [[http.services.cockpit.loadBalancer.servers]]
      url = "http://10.2.3.1:9090"

[http.routers]
  [http.routers.http-cockpit]
    rule = "Host(`cockpit.mistborn`)"
    service = "cockpit"
    entrypoints = ["web"]
    middlewares = ["mistborn_auth", "mistborn_headers"]
  [http.routers.https-cockpit]
    rule = "Host(`cockpit.mistborn`)"
    service = "cockpit"
    entrypoints = ["websecure"]
    middlewares = ["mistborn_auth", "mistborn_headers"]
    [http.routers.https-cockpit.tls]
      certresolver = "basic"

[http.middlewares]
  [http.middlewares.mistborn_auth.forwardAuth]
    address = "http://10.2.3.1:5000/auth/"
    trustForwardHeader = true
    [http.middlewares.mistborn_auth.forwardAuth.tls]
      insecureSkipVerify = true
  
  [http.middlewares.mistborn_headers.headers]
    hostsProxyHeaders = ['X-CSRFToken']
