[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/tls/cert.crt"
      keyFile = "/tls/cert.key"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"

[http.services]
  [http.services.cockpit.loadBalancer]
    [[http.services.cockpit.loadBalancer.servers]]
      url = "http://127.0.0.1:9090"

[http.routers]
  [http.routers.cockpit]
    rule = "Host(`cockpit.mistborn`)"
    service = "cockpit"
    entrypoints = ["web", "websecure"]
    middlewares = ["mistborn_auth@docker"]

[http.middlewares]
  [http.middlewares.mistborn_headers.headers]
    hostsProxyHeaders = ['X-CSRFToken']